// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkx5Fb0AInp8kDd_uOfmx0_XnmmSLzsHw',
    appId: '1:1049324260711:web:1940c5c27b166a239773c2',
    messagingSenderId: '1049324260711',
    projectId: 'loginauth-4c935',
    authDomain: 'loginauth-4c935.firebaseapp.com',
    databaseURL: 'https://loginauth-4c935-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginauth-4c935.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKod2gTQPWHrbPYnpEqKRZlRVdYkBqHvU',
    appId: '1:1049324260711:android:0f8ab89085138c469773c2',
    messagingSenderId: '1049324260711',
    projectId: 'loginauth-4c935',
    databaseURL: 'https://loginauth-4c935-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginauth-4c935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1us4WwsO4788iCNjubm43crivAqIXDhE',
    appId: '1:1049324260711:ios:8ee763840b4c27479773c2',
    messagingSenderId: '1049324260711',
    projectId: 'loginauth-4c935',
    databaseURL: 'https://loginauth-4c935-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginauth-4c935.appspot.com',
    iosClientId: '1049324260711-n9o02mfujdcbpqk5h9itlln6t12lqufh.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1us4WwsO4788iCNjubm43crivAqIXDhE',
    appId: '1:1049324260711:ios:8ee763840b4c27479773c2',
    messagingSenderId: '1049324260711',
    projectId: 'loginauth-4c935',
    databaseURL: 'https://loginauth-4c935-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginauth-4c935.appspot.com',
    iosClientId: '1049324260711-n9o02mfujdcbpqk5h9itlln6t12lqufh.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );
}
